<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.5 setup script
 * Date: Thu, 07 May 2015 07:36:24 +0000
$cfg['Servers'][$i]['extension'] = 'mysqli';
 */

/* Servers configuration */
$i = 0;

/* Server: docker mysql [3] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'docker';
$cfg['Servers'][$i]['host'] = 'mysql';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'my-secret-pw';

/* End of servers configuration */

$cfg['blowfish_secret'] = '500d4e0b5ca371.21574453';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '../../../mysql/';
$cfg['SaveDir'] = '/mysql/';
$cfg['LeftDisplayServers'] = true;
$cfg['VersionCheck'] = false;
$cfg['hide_connection_errors'] = false;
$cfg['UserprefsDisallow'] = array('VersionCheck');
?>
